apiVersion: v1
kind: Service
metadata:
  name: jira-postgres
  labels:
    app: jira
spec:
  ports:
    - port: 5432
  selector:
    app: jira
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jira-postgres
  labels:
    app: jira
spec:
  selector:
    matchLabels:
      app: jira
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira
        tier: postgres
    spec:
      containers:
      - image: $registryID.dkr.ecr.us-west-2.amazonaws.com/postgres:latest
        name: postgres
        env:
        - name: POSTGRES_USER
          value: jira_usr
        - name: POSTGRES_DB
          value: jira_db
        - name: POSTGRES_PASSWORD
          value: Password123
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
